### ISSUE TITLE
Invalid network configuration in the ops datastore

### ISSUE THREAD

**Issue by jktjkt** [CESNET/velia#3] opened 2021-06-03 11:32 UTC
```console-session
# netconf-cli-local 
libyang[0]: Schema node not found. (path: /ietf-interfaces:interfaces/ietf-interfaces:interface/ietf-ip:ipv6/ietf-ipv6-unicast-routing:ipv6-router-advertisements)
libyang[0]: Invalid value "/ietf-interfaces:interfaces/ietf-interfaces:interface/ietf-ip:ipv6/ietf-ipv6-unicast-routing:ipv6-router-advertisements" of "deviation".
Connected via NETCONF [datastore target: operational]
/> get
libyang[0]: Invalid value "cla-network:dhcp" in "source-protocol" element. (path: /ietf-routing:routing/ribs/rib[name='ipv4-master']/routes/route[1]/source-protocol)
[ERR]: Failed to parse <get> reply.
Failed to receive an RPC reply
```

This is with a SW image which [pins all deps and `velia` to their current `master`s](https://gerrit.cesnet.cz/c/CzechLight/br2-external/+/4265). On the other hand, the [`master` of `br2-external`](https://gerrit.cesnet.cz/c/CzechLight/br2-external/+/4257) works fine.

**Comment by peckato1** [comment] 2021-06-04 10:49
The problem is in 2d87fd1d0a4dc93816822d9d72d00d8f8e61ce37. The deviation statement is OK with yanglint and sysrepo, but netopeer2 seems to struggle with it. I have opened an issue https://github.com/CESNET/netopeer2/issues/914.

**Comment by peckato1** [comment] 2021-06-04 18:32
Fixed in https://gerrit.cesnet.cz/c/CzechLight/br2-external/+/4265/3

**Closed by peckato1** 2021-06-04 18:32 UTC
